### ISSUE TITLE
ETC spec for forkid discover protocol

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/multi-geth-fork#87]
- https://github.com/etclabscore/multi-geth/pull/82#discussion_r358360780
- https://eips.ethereum.org/EIPS/eip-2124
- https://eips.ethereum.org/EIPS/eip-2364

Need to spec and ensure that ETC clients and networks implementing this protocol know how to do this in a consistent way, _eg_ is 1920000 a fork? I say no, but this should be up for discussion and review.

**Comment by tzdybal** [comment]
Totally agree that 1920000 is not a fork for us. It's a fork for ETH, not ETC.
I really don't like EIP-2124 ("separating networks" can make it harder to establish peer list, IMHO), and EIP-2364 (why use both genesis hash and forkid (which "contains" information about genesis hash)?).

The good part is, that change is implemented as new version of a protocol, instead of changing the current one.

**Comment by meowsbits** [comment]
See https://github.com/ethereumclassic/ECIPs/pull/247

**Comment by meowsbits** [comment]
Closing, will manage idea at ECIPs context.
